include:
  - local: .gitlab/build.yml
  - local: .gitlab/docker.yml
  - local: .gitlab/docker/builder/gitlab.yml

stages:
  - docker
  - build
  - run

build test intel_mips prpl webui:
  extends: .build test config
