include:
  - local: .gitlab/build.yml
  - local: .gitlab/docker.yml
  - local: .gitlab/docker/builder/gitlab.yml
  - local: .gitlab/docker/testbed/gitlab.yml
  - local: .gitlab/docker/sdk/gitlab.yml
  - local: .gitlab/testbed.yml
  - local: .gitlab/testbed/nec-wx3000hp.yml

stages:
  - docker
  - docker test
  - docker deploy
  - build
  - docker SDK
  - docker SDK test
  - docker SDK deploy
  - run

build test intel_mips prpl webui:
  extends: .build test config
  variables:
    CI_BUILD_CONFIG_EXTRA: >
      +BUILD_LOG +SDK

build test ipq40xx prpl webui:
  extends: .build test config

build test mvebu prpl webui:
  extends: .build test config

run test NEC WX3000HP with system on NAND:
  dependencies:
    - build test intel_mips prpl webui
  extends: .nec-wx3000hp testbed
  variables:
    LABGRID_TARGET: "$DUT_BOARD-nand"
    TFTP_IMAGE_FILENAME: AX3000_1600_ETH_11AXUCI_ASURADA-squashfs-fullimage.img
