.build test config:
  stage: build
  image: "$CI_REGISTRY_IMAGE/builder:latest"
  tags:
    - firmware-builder
  rules:
    - if: '$CI_COMMIT_BRANCH == "prplwrt"'
      when: delayed
      start_in: '8 hours'
  before_script:
    - touch .build_failed

  script:
    - mkdir logs

    - export CI_BUILD_CONFIG="$(echo $CI_JOB_NAME | sed 's/build test \(.*\)/\1/')"
    - scripts/gen_config.py $CI_BUILD_CONFIG 2>&1 | tee logs/build.log
    - echo CONFIG_BUILD_LOG=y >> .config
    - make defconfig | tee --append logs/build.log
    - make -j $(nproc) || make -j1 V=s 2>&1 | tee --append logs/build.log

    - rm .build_failed

  after_script:
    - test -f .build_failed && .gitlab/scripts/prpl-jira.py build_failure

  artifacts:
    expire_in: 1 month
    when: always
    paths:
      - bin
      - logs
  cache:
    key: openwrt-downloads
    paths:
      - dl/
