build Docker image sdk:
  stage: docker SDK
  dependencies:
    - build test intel_mips prpl webui
  extends: .build Docker image
  before_script:
    - tar xf bin/targets/intel_mips/xrx500/openwrt-sdk-intel_mips-xrx500_gcc-*_musl.Linux-x86_64.tar.xz --strip=1 -C .gitlab/docker/sdk
